# Вычисления с помощью Numpy

In [1]:
import numpy as np

### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10], 
            [1, 7]])


In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
a_centered_sp = np.dot(a[0], a[1])
a_centered_sp

50

In [7]:
np.shape(a)

(5, 2)

**Вот тут скобок не хватет и где-то ещё ошибка:**

In [8]:
a_centered_sp = a_centered_sp / np.shape(a)[0]-1

In [9]:
a_centered_sp

9.0